version: '3.8'

services:
  mysql_wp:
    image: mysql:8.0
    container_name: mysql_wp_temp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_migrate
    ports:
      - "33066:3306"
    volumes:
      - ./wordpress:/docker-entrypoint-initdb.d
